const CREATED_CODE = 201;
const ERROR_CODE = 400;
const NOT_FOUND_CODE = 404;
const SERVER_ERROR_CODE = 500;

module.exports = {
  NOT_FOUND_CODE,
  SERVER_ERROR_CODE,
  CREATED_CODE,
  ERROR_CODE,
};
